name = "First_sip_of_Lean"
version = "0.1.0"
defaultTargets = ["first_sip_of_lean"]

[[lean_lib]]
name = "FirstSipOfLean"

[[lean_exe]]
name = "first_sip_of_lean"
root = "Main"

[[require]]
name  = "mathlib"
git   = "https://github.com/leanprover-community/mathlib4.git"
rev   = "master"
